# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T3UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.isoValue = QtWidgets.QSlider(self.centralwidget)
        self.isoValue.setGeometry(QtCore.QRect(80, 270, 311, 22))
        self.isoValue.setMaximum(2500)
        self.isoValue.setProperty("value", 500)
        self.isoValue.setOrientation(QtCore.Qt.Horizontal)
        self.isoValue.setObjectName("isoValue")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 210, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.modul_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.modul_comboBox.setGeometry(QtCore.QRect(280, 120, 291, 51))
        self.modul_comboBox.setObjectName("modul_comboBox")
        self.modul_comboBox.addItem("")
        self.modul_comboBox.addItem("")
        self.modul_comboBox.addItem("")
        self.opacity = QtWidgets.QSlider(self.centralwidget)
        self.opacity.setGeometry(QtCore.QRect(80, 360, 311, 22))
        self.opacity.setMaximum(100)
        self.opacity.setSingleStep(10)
        self.opacity.setProperty("value", 1)
        self.opacity.setOrientation(QtCore.Qt.Horizontal)
        self.opacity.setObjectName("opacity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 310, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(80, 120, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load.setFont(font)
        self.load.setObjectName("load")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Iso-Value"))
        self.modul_comboBox.setItemText(0, _translate("MainWindow", "Module "))
        self.modul_comboBox.setItemText(1, _translate("MainWindow", "Surface rendering"))
        self.modul_comboBox.setItemText(2, _translate("MainWindow", "Ray casting rendering"))
        self.label_3.setText(_translate("MainWindow", "opacity"))
        self.load.setText(_translate("MainWindow", "load data"))
        self.label_4.setText(_translate("MainWindow", "Medical data visualization "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
